both upgrade cljsh from github and lein-repls from clojars seem to work

diff --git a/bin/cljsh b/bin/cljsh
--- a/bin/cljsh
+++ b/bin/cljsh
@@ -144,29 +144,35 @@ function startRepls ()
 function upgradeCljsh ()
 {
 if [ "$CLJSH_DIR" != "" ]; then
-		echo "The upgrade task is not meant to be run from a checkout."
-		exit 1
+	displayAlert "ERROR: The cljsh upgrade is not meant to be run from a checkout."
+	exit 1
 fi
 if [ "$SNAPSHOT" = "YES" ]; then
-		echo "The upgrade task is only meant for stable releases."
-		exit 1
+	displayAlert "The upgrade task is only meant for stable releases."
+	exit 1
 fi
 if [ ! -w "$SCRIPT" ]; then
-		echo "You do not have permission to upgrade the installation in $SCRIPT"
-		exit 1
+	displayAlert "ERROR: You do not have permission to upgrade the installation in $SCRIPT"
+	exit 1
 else
-		#https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION
-		#https://raw.github.com/franks42/lein-repls/stable/bin/cljsh.sh
 		# if [ `curl https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION` == `cljsh -V` ]; then echo YES; fi
 		echo "Downloading cljsh stable version number..."
-		CLJSH_STABLE_VERSION=`curl https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION`
-		echo "The script at $SCRIPT with version $CLJSH_VERSION  will be upgraded to the latest stable version (" "$CLJSH_STABLE_VERSION" ")."
-		echo -n "Do you want to continue [Y/n]? "
+		TARGET="/tmp/cljsh-$$-upgrade"
+		CLJSH_SCRIPT_URL="https://raw.github.com/franks42/lein-repls/stable/bin/cljsh"
+		$HTTP_CLIENT "$TARGET" "$CLJSH_SCRIPT_URL"
+		# CLJSH_STABLE_VERSION=`curl https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION`
+		CLJSH_STABLE_VERSION="`cat "$TARGET" | grep 'CLJSH_VERSION='`"
+		if [ "$CLJSH_STABLE_VERSION" == "" ]; then 
+			displayAlert "ERROR: unable to obtain stable cljsh version info from github."
+			exit 1;
+		fi
+		echo "$SCRIPT with version $CLJSH_VERSION  will be upgraded to the latest stable version (" "$CLJSH_STABLE_VERSION" ")."
+		/bin/echo -n "Do you want to upgrade to stable version \""$CLJSH_STABLE_VERSION"\" [y/N]? "
 		read RESP
 		case "$RESP" in
-				y|Y|"")
+				y|Y)
 						echo
-						echo "Upgrading..."
+						echo "Upgrading cljsh..."
 						TARGET="/tmp/cljsh-$$-upgrade"
 						CLJSH_SCRIPT_URL="https://raw.github.com/franks42/lein-repls/stable/bin/cljsh"
 						$HTTP_CLIENT "$TARGET" "$CLJSH_SCRIPT_URL" \
@@ -175,11 +181,53 @@ else
 								&& "$SCRIPT" -v
 						exit $?;;
 				*)
-						echo "Aborted."
+						echo "Cljsh upgrade aborted."
 						exit 1;;
 		esac
 fi
 }
+
+
+# up/down/side-grade lein-repls plugin
+# lein_repls_version="`cljsh -c '(println cljsh.core/lein-repls-version)'`"
+
+
+function upgradeLeinRepls ()
+{
+	echo "Determining if lein-repls is installed..."
+	if [ "`lein help | grep 'repls'`" != "" ]; then 
+		CURRENT_LEIN_REPLS_VERSION="`cljsh -c '(println cljsh.core/lein-repls-version)'`"
+		if [ "$CURRENT_LEIN_REPLS_VERSION" == "" ]; then
+			displayAlert "ERROR: unable to obtain current lein-repls version - make sure repls-server is running.";
+			exit 1
+		fi
+		echo "Current lein-repls version is: \"$CURRENT_LEIN_REPLS_VERSION\".";
+	else
+		echo "No lein-repls plugin installed (yet).";
+	fi
+	echo "Downloading lein-repls info from clojars..."
+	TMP_ALL_JARS="/tmp/cljsh-$$-all-jars"
+	curl "http://clojars.org/repo/all-jars.clj" > "$TMP_ALL_JARS"
+	echo "Available versions on clojars:"
+	cat "$TMP_ALL_JARS" | grep 'lein-repls'
+	/bin/echo -n "Enter lein-repls version (e.g. 1.2.3) to install/upgrade-to ([return]: do nothing): "
+	read RESP;
+	if [ "$RESP" != "" ]; then
+		echo "Installing/Upgrading-to lein-repls version "$RESP"...";
+		set -x
+		if [ "$CURRENT_LEIN_REPLS_VERSION" != "" ]; then
+			lein plugin uninstall lein-repls "$CURRENT_LEIN_REPLS_VERSION" && lein plugin install lein-repls "$RESP"
+		else
+			lein plugin install lein-repls "$RESP"
+		fi
+		exit $?
+	else
+		echo "lein-repls upgrade aborted.";
+		exit 1;
+	fi
+
+}
+
 
 # Clojure code snippets
 
@@ -228,7 +276,7 @@ CLJ_CODE_BEFORE=${CLJ_CODE}
 CLJ_CODE_AFTER=
 
 # command line option processing
-while [ "${!OPTIND}" == "-" ] || getopts ":darwplLPgGhtUvVm:c:s:e:f:i:" opt; do
+while [ "${!OPTIND}" == "-" ] || getopts ":darwplLPgGhtuUvVm:c:s:e:f:i:" opt; do
   case $opt in
     c) 	# clojure code statements expected as options value
     	echo "${OPTARG}" >> ${CLJ_CODE}
@@ -299,6 +347,10 @@ while [ "${!OPTIND}" == "-" ] || getopts ":darwplLPgGhtUvVm:c:s:e:f:i:" opt; do
       ;;
     a) 	# use applescript dialogs/alerts when available
       CLJSH_ALERT_DIALOG=1
+      ;;
+    u) 	# upgrade lein-repls
+			upgradeLeinRepls
+			exit 0
       ;;
     U) 	# upgrade cljsh
 			upgradeCljsh
