type in version...

diff --git a/bin/cljsh b/bin/cljsh
--- a/bin/cljsh
+++ b/bin/cljsh
@@ -155,35 +155,30 @@ if [ ! -w "$SCRIPT" ]; then
 	displayAlert "ERROR: You do not have permission to upgrade the installation in $SCRIPT"
 	exit 1
 else
-		# if [ `curl https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION` == `cljsh -V` ]; then echo YES; fi
-		echo "Downloading cljsh stable version number..."
-		TARGET="/tmp/cljsh-$$-upgrade"
-		CLJSH_SCRIPT_URL="https://raw.github.com/franks42/lein-repls/stable/bin/cljsh"
-		$HTTP_CLIENT "$TARGET" "$CLJSH_SCRIPT_URL"
-		# CLJSH_STABLE_VERSION=`curl https://raw.github.com/franks42/lein-repls/stable/bin/CLJSH_VERSION`
-		CLJSH_STABLE_VERSION="`cat "$TARGET" | grep 'CLJSH_VERSION='`"
-		if [ "$CLJSH_STABLE_VERSION" == "" ]; then 
-			displayAlert "ERROR: unable to obtain stable cljsh version info from github."
-			exit 1;
-		fi
-		echo "$SCRIPT with version $CLJSH_VERSION  will be upgraded to the latest stable version (" "$CLJSH_STABLE_VERSION" ")."
-		/bin/echo -n "Do you want to upgrade to stable version \""$CLJSH_STABLE_VERSION"\" [y/N]? "
-		read RESP
-		case "$RESP" in
-				y|Y)
-						echo
-						echo "Upgrading cljsh..."
-						TARGET="/tmp/cljsh-$$-upgrade"
-						CLJSH_SCRIPT_URL="https://raw.github.com/franks42/lein-repls/stable/bin/cljsh"
-						$HTTP_CLIENT "$TARGET" "$CLJSH_SCRIPT_URL" \
-								&& mv "$TARGET" "$SCRIPT" \
-								&& chmod +x "$SCRIPT" \
-								&& "$SCRIPT" -v
-						exit $?;;
-				*)
-						echo "Cljsh upgrade aborted."
-						exit 1;;
-		esac
+	echo "Downloading cljsh stable version number..."
+	TARGET="/tmp/cljsh-$$-upgrade"
+	CLJSH_SCRIPT_URL="https://raw.github.com/franks42/lein-repls/stable/bin/cljsh"
+	$HTTP_CLIENT "$TARGET" "$CLJSH_SCRIPT_URL"
+	CLJSH_STABLE_VERSION="$( cat "$TARGET" | grep CLJSH_VERSION=\" )"
+	if [ "$CLJSH_STABLE_VERSION" == "" ]; then 
+		displayAlert "ERROR: unable to obtain stable cljsh version info from github."
+		exit 1;
+	fi
+	echo "cljsh at \"$SCRIPT\" has version \"$CLJSH_VERSION\"  and the latest stable version is \"$CLJSH_STABLE_VERSION\".")."
+	/bin/echo -n "Do you want to upgrade to stable version \""$CLJSH_STABLE_VERSION"\" [y/N]? "
+	read RESP
+	case "$RESP" in
+			y|Y)
+					echo
+					echo "Upgrading cljsh..."
+							&& mv "$TARGET" "$SCRIPT" \
+							&& chmod +x "$SCRIPT" \
+							&& "$SCRIPT" -v
+					exit $?;;
+			*)
+					echo "Cljsh upgrade aborted."
+					exit 1;;
+	esac
 fi
 }
 
